### ISSUE TITLE
atrcopy 8.1 kboot file processing is broken

### ISSUE THREAD

**Issue by ChoccyHobNob** [robmcmullen/atrcopy#13]
I can no longer extract the file from a kboot. 
listing a kboot now gives a traceback. 
```
atrcopy kttst.atr        
kttst.atr: ATR Disk Image (size=14720 (115x128B), crc=0 flags=0 unused=0) KBoot Format: 14265 byte executable
Traceback (most recent call last):
  File "/usr/local/bin/atrcopy", line 6, in <module>
    atrcopy.run()
  File "/usr/local/lib/python3.6/site-packages/atrcopy/__init__.py", line 589, in run
    list_files(parser.image, options.files, options.crc, options.metadata)
  File "/usr/local/lib/python3.6/site-packages/atrcopy/__init__.py", line 166, in list_files
    print("%s%s" % (dirent, extra))
  File "/usr/local/lib/python3.6/site-packages/atrcopy/ataridos.py", line 100, in __str__
    return "File #%-2d (%s) %03d %-8s%-3s  %03d" % (self.file_num, self.summary, self.starting_sector, self.basename.decode("latin1"), self.ext.decode("latin1"), self.num_sectors)
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by robmcmullen** [comment]
It's fixed in the source now, but it doesn't recognize kboot images that it itself creates, so there are more problems. I'll put out a new version when I fix that.

**Comment by robmcmullen** [comment]
Try 8.2 now.

**Comment by ChoccyHobNob** [comment]
I swear it used to support extracting the xex from the kboot. I'm either getting the syntax wrong or it no longer does it or my mind imagined the functionality in the first place!

atrcopy file.atr x
atrcopy file.atr x file.xex

??

**Comment by robmcmullen** [comment]
It seems to be working here:
```
$ atrcopy arkanoid2.atr x KBOOT.XEX
arkanoid2.atr: ATR Disk Image (size=39296 (307x128B), crc=0 flags=0 unused=0) KBoot Format: 38911 byte executable
extracting KBOOT.XEX -> KBOOT.XEX
```
Can you upload your ATR file?

**Comment by robmcmullen** [comment]
It is case sensitive, maybe that's it? (I need to fix that.)

**Comment by ChoccyHobNob** [comment]
Ah that's my problem. The filename has to be KBOOT.XEX

I was trying ‘atrcopy 180.atr x 180.xex’ I had it in my head that because there was only one file in the image I could extract it using any name I liked. Just me being sloppy

Thanks!
