### ISSUE TITLE
Problem with specific DOS 3.3 image

### ISSUE THREAD

**Issue by jepler** [robmcmullen/atrcopy#14]
I was trying atrcopy with https://archive.org/download/Arcade_Games_Collection_Side_1 and found that it couldn't list the catalog.
An Apple //e emulator (mame) can.

It appears 'real Apple DOS 3.3' ignores at least some out of range values for 'sector size' in the VTOC. This particular image has a VTOC sector size of 1 byte! which is super broken.

The following change makes my particular disk image work. However, I don't know if it's the "most correct" change. If you like, I can propose this change as a PR instead. Please let me know.

```patch
diff --git a/atrcopy/dos33.py b/atrcopy/dos33.py
index 96b1010..a4b675e 100644
--- a/atrcopy/dos33.py
+++ b/atrcopy/dos33.py
@@ -447,6 +447,8 @@ class Dos33DiskImage(DiskImageBase):
         values = data[0:self.vtoc_type.itemsize].view(dtype=self.vtoc_type)[0]
         self.header.first_directory = self.header.sector_from_track(values['cat_track'], values['cat_sector'])
         self.header.sector_size = int(values['sector_size'])
+        if self.header.sector_size == 1:
+            self.header.sector_size = 256
         self.header.max_sectors = int(values['num_tracks']) * int(values['sectors_per_track'])
         self.header.ts_pairs = int(values['max_pairs'])
         self.header.dos_release = values['dos_release']
```

**Comment by jepler** [comment]
I can't find any evidence that DOS 3.3 supported non-256-byte sectors, so ignoring this value altogether might be better. Of course, I don't know much about DOS extensions which might exist in the world. The one [very opinionated(!)](https://htmlpreview.github.io/?https://github.com/Michaelangel007/apple2_dos33/blob/master/dos33.html) DOS 3.3 disassembly I referred to didn't find any use of the value stored there.

**Comment by robmcmullen** [comment]
Thanks, I added a log message when this is found and set the sector size to 256 bytes.
