### ISSUE TITLE
Some KBOOT disks not being identified

### ISSUE THREAD

**Issue by ChoccyHobNob** [robmcmullen/atrcopy#5]
I've been running atrcopy on a few of my collected disk images and I've noticed that quite a few that are identified in the name as [k-file] and indeed when booted have the "k" in the top left corner are nonetheless not identified as KBOOT by atrcopy. 

I've attached one which exhibits this behaviour. 

The output I get is this...
`atrcopy -v /Users/steve/Emulation/A8/Zipper\ \[PCS\]/Zipper\ \(1984\)\(Small\)\[PCS\]\[k-file\].atr 
Loading file /Users/steve/Emulation/A8/Zipper [PCS]/Zipper (1984)(Small)[PCS][k-file].atr
Trying MIME type application/vnd.atari8bit.atr
DEBUG:atrcopy.parsers:Trying <class 'atrcopy.kboot.KBootImage'>
INFO:atrcopy.parsers:parser isn't KBootSegmentParser: Sector 360 out of range
DEBUG:atrcopy.parsers:Trying <class 'atrcopy.spartados.SpartaDosDiskImage'>
INFO:atrcopy.parsers:parser isn't SpartaDosSegmentParser: Invalid SpartaDos parameters in boot header
DEBUG:atrcopy.parsers:Trying <class 'atrcopy.ataridos.AtariDosDiskImage'>
INFO:atrcopy.parsers:parser isn't AtariDosSegmentParser: Sector 360 out of range
DEBUG:atrcopy.parsers:Trying <class 'atrcopy.ataridos.BootDiskImage'>
Found parser Atari Boot Disk Image
/Users/steve/Emulation/A8/Zipper [PCS]/Zipper (1984)(Small)[PCS][k-file].atr: ATR Disk Image (size=30720 (240x128B), crc=0 flags=0 unused=0) Boot Disk`

[unknown kboot.zip](https://github.com/robmcmullen/atrcopy/files/1338111/unknown.kboot.zip)

**Comment by robmcmullen** [comment]
Thanks! I see the same error here, so I'll take a look at it.

**Comment by robmcmullen** [comment]
Version 6.1 should be pip installable

**Comment by ChoccyHobNob** [comment]
I've had a chance to test this with a bunch of kboot files and it spots all of them now. Cheers!
