### ISSUE TITLE
Program crash on create new disk file. 

### ISSUE THREAD

**Issue by ChoccyHobNob** [robmcmullen/atrcopy#8]
`atrcopy new.atr create -f dos2ed+2.5`
Fails with a crash

`Traceback (most recent call last):
  File "/usr/local/bin/atrcopy", line 6, in <module>
    atrcopy.run()
  File "/usr/local/lib/python2.7/site-packages/atrcopy/__init__.py", line 541, in run
    create_image(options.template[0], disk_image_name)
  File "/usr/local/lib/python2.7/site-packages/atrcopy/__init__.py", line 337, in create_image
    data, inf = get_template_data(template)
  File "/usr/local/lib/python2.7/site-packages/atrcopy/__init__.py", line 324, in get_template_data
    raise InvalidDiskImage("Template disk image %s not found" % template)
atrcopy.errors.InvalidDiskImage: Template disk image dos2ed+2.5 not found`

I uninstalled and reinstalled atrcopy, same problem
`pip uninstall atrcopy
Uninstalling atrcopy-6.2.0:
  /usr/local/bin/atrcopy
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/atrcopy-6.2.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/atrcopy/__init__.py
  /usr/local/lib/python2.7/site-packages/atrcopy/__init__.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/_metadata.py
  /usr/local/lib/python2.7/site-packages/atrcopy/_metadata.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/ataridos.py
  /usr/local/lib/python2.7/site-packages/atrcopy/ataridos.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/cartridge.py
  /usr/local/lib/python2.7/site-packages/atrcopy/cartridge.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/diskimages.py
  /usr/local/lib/python2.7/site-packages/atrcopy/diskimages.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/dos33.py
  /usr/local/lib/python2.7/site-packages/atrcopy/dos33.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/errors.py
  /usr/local/lib/python2.7/site-packages/atrcopy/errors.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/fstbt.py
  /usr/local/lib/python2.7/site-packages/atrcopy/fstbt.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/kboot.py
  /usr/local/lib/python2.7/site-packages/atrcopy/kboot.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/mame.py
  /usr/local/lib/python2.7/site-packages/atrcopy/mame.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/parsers.py
  /usr/local/lib/python2.7/site-packages/atrcopy/parsers.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/segments.py
  /usr/local/lib/python2.7/site-packages/atrcopy/segments.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/spartados.py
  /usr/local/lib/python2.7/site-packages/atrcopy/spartados.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/standard_delivery.py
  /usr/local/lib/python2.7/site-packages/atrcopy/standard_delivery.pyc
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2dd.atr
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2dd.atr.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2ed+2.5.atr
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2ed+2.5.atr.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2ed.atr
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2ed.atr.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2sd+2.0s.atr
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2sd+2.0s.atr.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2sd.atr
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos2sd.atr.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos33.dsk
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos33.dsk.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos33autobrun.dsk
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/dos33autobrun.dsk.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/no-json.dsk
  /usr/local/lib/python2.7/site-packages/atrcopy/templates/no-json.dsk.inf
  /usr/local/lib/python2.7/site-packages/atrcopy/utils.py
  /usr/local/lib/python2.7/site-packages/atrcopy/utils.pyc
Proceed (y/n)? y
  Successfully uninstalled atrcopy-6.2.0`

`» ChoccyBook:Altirra-3.00 >pip install atrcopy 
Collecting atrcopy
Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from atrcopy)
Requirement already satisfied: future in /usr/local/lib/python2.7/site-packages (from atrcopy)
Installing collected packages: atrcopy
Successfully installed atrcopy-6.2.0`

`» ChoccyBook:Altirra-3.00 >atrcopy new.atr create -f dos2ed+2.5
Traceback (most recent call last):
  File "/usr/local/bin/atrcopy", line 6, in <module>
    atrcopy.run()
  File "/usr/local/lib/python2.7/site-packages/atrcopy/__init__.py", line 541, in run
    create_image(options.template[0], disk_image_name)
  File "/usr/local/lib/python2.7/site-packages/atrcopy/__init__.py", line 337, in create_image
    data, inf = get_template_data(template)
  File "/usr/local/lib/python2.7/site-packages/atrcopy/__init__.py", line 324, in get_template_data
    raise InvalidDiskImage("Template disk image %s not found" % template)
atrcopy.errors.InvalidDiskImage: Template disk image dos2ed+2.5 not found`

**Comment by robmcmullen** [comment]
The workaround for now is to include the file extension of the template, e.g. ``atrcopy new.atr create -f dos2ed+2.5.atr``

**Comment by robmcmullen** [comment]
Try version 6.5.0 (available through pip now).
